### PR TITLE
Full URL visit support

### PR DESCRIPTION
**Pull request by hiroshi**
- [x] just add failed test
- [x] Fix it!

I merged railsware/rack_session_access#15 to run tests.

### CODE REVIEW

**Comment by ayanko** [comment]
@hiroshi 
You provided "some solution". But where is description of the problem?

**Comment by hiroshi** [comment]
> You provided "some solution". But where is description of the problem?

Sorry.

The problem is that `#set_rack_session" isn't aware of the domain of sessions. When I use full urls on a `#vist`, there was not way to share session with `#set_rack_session`.
My application recognizes subdomains of request urls, so I need to specify full urls for request specs.

I don't think my implementation is good one, but it works for me, at least.
I hope you see the problem.

Please let me know if my description of the problem is not clear for you :)

**Comment by ayanko** [comment]
* You tested new feature **ONLY** against `rack_test` driver. AFAIK it does not supports custom domains (not sure)

* We should ensure that when you set rack session key value for domain `example1.localhost` it should not be set for any other domain e.g `example2.localhost`.

* new feature should supports multiple capybara drivers. At least it should be tested against two:
 * rack_test (no separate app process)
 * selenium (starts app server process)

**Comment by jerefrer** [comment]
Thanks a bunch @hiroshi, you saved my day :)
I couldn't manage to keep the session when visiting a subdomain, before I found your fix.
Great day to you !

**Pull request closed without merging**
